[world]
name = "Ponzi Land"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://ponzi.land"
seed = "ponzi_land-testing-3"

[world.socials]
x = "https://x.com/ponzidotland"
discord = "https://discord.gg/ponziland"
github = "https://github.com/Runelabsxyz/PonziLand"
telegram = "https://t.me/dojoengine"

[namespace]
default = "ponzi_land"


[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"
#world = "0x0159a8d45365dce1aa357933e2e2e0a9290a41f275e100ae549092c3bb91067d"

[writers]
# We need to be a writer to add events...
"ponzi_land" = ["ponzi_land-actions", "ponzi_land-auth"]

[init_call_args]
"ponzi_land-actions" = [
    "0x05735fa6be5dd248350866644c0a137e571f9d637bb4db6532ddd63a95854b58", # Token address (eSTRK)
    "128000000000000000000",                                              # start price (low)
    "0",                                                                  # start price (high)
    "1000000000000000000",                                                # floor price (low)
    "0",                                                                  # floor price (high)
    "100",                                                                # Decay rate (100)
    "0x00000005dd3D2F4429AF886cD1a3b08289DBcEa99A294197E9eB43b0e0325b4b", # Ekubo core contract address
]

"ponzi_land-auth" = [
    "0x021fBAE9F9343873ab25eC14d287A1170b676C73c97906790ef91F5428dBdbad", # Owner address
    "0x001c012e0e8408af283483480f18c0f7a313e76012a06b158913d71cc304ba3b", # Verifier
]

"ponzi_land-token_registry" = [
    "7",                                                                  # 4 tokens,
    "0x05735fa6be5dd248350866644c0a137e571f9d637bb4db6532ddd63a95854b58", # nftSTRK
    "0x40025cec149bf1f58d2e34a6924605b571a5fce7b798a47ec52cfbd3ff68b6e",  # ePAPER
    "0x78c1138aa1cfd27436b26279d5ac4e3f8f5a432927d85d22b2a2e7c0e5528b4",  # eLORDS
    "0x74ad80778e07102902abdec71e0161023b45d1204c29e2c4ec3befab3bb82f5",  # eBROTHER
]
