[package]
cairo-version = "=2.9.4"
name = "ponzi_land"
version = "1.4.0"
edition = "2023_01"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                    # scarb run migrate
spawn = "sozo execute ponzi_land-actions spawn --wait"    # scarb run spawn
move = "sozo execute ponzi_land-actions move -c 1 --wait" # scarb run move

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.18.0" }
ekubo = { git = "https://github.com/EkuboProtocol/abis", rev = "edb6de8c9baf515f1053bbab3d86825d54a63bc3" }

[profile.sepolia]

[profile.mainnet]

[profile.mainnet-test]

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.9.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }
